compute005
1,2,3,4
[33mWARN: gym.spaces.Box autodetected dtype as <class 'numpy.float32'>. Please provide explicit dtype.[0m
9000 3
Box(3, 60, 50)
/home/zihan/anaconda3/envs/exp/lib/python3.6/site-packages/gym/envs/registration.py:14: PkgResourcesDeprecationWarning: Parameters to load are deprecated.  Call .resolve and .require separately.
  result = entry_point.load(False)
[33mWARN: gym.spaces.Box autodetected dtype as <class 'numpy.float32'>. Please provide explicit dtype.[0m
/home/zihan/anaconda3/envs/exp/lib/python3.6/site-packages/gym/envs/registration.py:14: PkgResourcesDeprecationWarning: Parameters to load are deprecated.  Call .resolve and .require separately.
  result = entry_point.load(False)
Process Process-2:
Traceback (most recent call last):
  File "/home/zihan/anaconda3/envs/exp/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/zihan/anaconda3/envs/exp/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/zihan/Soft-Decision-Tree/image_based_envs/mp_cdt_ppo_gae_discrete_cnn.py", line 194, in run
    a, prob = model.choose_action(s)
  File "/home/zihan/Soft-Decision-Tree/image_based_envs/mp_cdt_ppo_gae_discrete_cnn.py", line 164, in choose_action
    prob = self.pi(s).squeeze()
  File "/home/zihan/Soft-Decision-Tree/image_based_envs/mp_cdt_ppo_gae_discrete_cnn.py", line 83, in pi
    return self.cdt.forward(x, LogProb=False)[1].to(x.device)
  File "/home/zihan/Soft-Decision-Tree/image_based_envs/image_cascade_tree.py", line 131, in forward
    fl_probs = self.feature_learning_forward()  # (batch_size, num_fl_leaves)
  File "/home/zihan/Soft-Decision-Tree/image_based_envs/image_cascade_tree.py", line 48, in feature_learning_forward
    path_prob = self.sigmoid(self.beta_fl*self.fl_inner_nodes(self.aug_data))
RuntimeError: binary_op(): expected both inputs to be on same device, but input a is on cuda:0 and input b is on cuda:2
slurmstepd: error: *** JOB 216807 ON compute005 CANCELLED AT 2020-06-09T10:48:14 ***
/home/zihan/anaconda3/envs/exp/lib/python3.6/multiprocessing/semaphore_tracker.py:143: UserWarning: semaphore_tracker: There appear to be 3 leaked semaphores to clean up at shutdown
  len(cache))
